# Generated by Django 5.1 on 2024-08-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=150, verbose_name='Title Arabic')),
                ('title_en', models.CharField(max_length=150, verbose_name='Title English')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Salary')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Phone')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='PersonJobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary')),
                ('years_of_experince', models.PositiveIntegerField(verbose_name='Years Of Experince')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_job', to='core.job')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_person', to='core.person')),
            ],
            options={
                'verbose_name': 'PersonJobDetail',
                'verbose_name_plural': 'PersonJobDetails',
            },
        ),
    ]
