# Generated by Django 5.1 on 2024-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(max_length=15, unique=True, verbose_name='Mobile Phone'),
        ),
    ]
